all:	alarmClock clock

alarmClock: alarmClock.c
	gcc -Wall -o alarmClock alarmClock.c

clock:	clock.c
	gcc -Wall -o clock clock.c

stringTokenizer:	stringTokenizer.c
	gcc -Wall -o stringTokenizer stringTokenizer.c
	
clean:	
	rm -f alarmClock clock stringTokenizer

